[package]
name = "game"
version = "0.1.0"
edition = "2021"

[dependencies]
phosphor = { path = "../phosphor" }
phosphor_3d = { path = "../phosphor_3d" }
phosphor_fmod = { path = "../phosphor_fmod" }
dolly = "0.4"
ezlogger = "0.1"
