[package]
name = "o"
version = "0.1.0"
edition = "2021"

[dependencies]
grr = "0.8"
glutin = "0.29"
glam = "0.22"
image = "0.24"
bytemuck = { version = "1.4", features = ["derive"] }
anyhow = "1.0"
log = "0.4"
env_logger = "0.9"