[package]
name = "phosphor_editor"
version = "0.1.0"
edition = "2021"

[dependencies]
phosphor = { path = "../phosphor" }
phosphor_3d = { path = "../phosphor_3d" }
phosphor_imgui = { path = "../phosphor_imgui" }
ezlogger = "0.1"
