[package]
name = "phosphor_ui"
version = "0.1.0"
edition = "2021"

[dependencies]
phosphor = { path = "../phosphor" }
imgui = { git = "https://github.com/imgui-rs/imgui-rs", features=["docking"] }
imgui-winit-support = { git = "https://github.com/imgui-rs/imgui-rs" }
