[package]
name = "phosphor_fmod"
version = "0.1.0"
edition = "2021"

[dependencies]
phosphor = { path = "../phosphor" }
phosphor_3d = { path = "../phosphor_3d" }
libfmod = "2.2.605"
serde = { version = "1.0", features = ["derive"] }
linkme = "0.3"
