[package]
name = "phosphor_3d"
version = "0.1.0"
edition = "2021"

[dependencies]
phosphor = { path = "../phosphor" }
serde = { version = "1.0", features = ["derive"] }
linkme = "0.3"
rand = "0.8"
log_once = { path = "../../log_once" }
